// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nI4LsQkKBwvYtA0zYZ7gdQBYR1u_OGg',
    appId: '1:885465995791:web:02e0f2f5eee24d2fb4217a',
    messagingSenderId: '885465995791',
    projectId: 'authenticated-user-dashb-b0b3f',
    authDomain: 'authenticated-user-dashb-b0b3f.firebaseapp.com',
    storageBucket: 'authenticated-user-dashb-b0b3f.firebasestorage.app',
    measurementId: 'G-LV7VD6H930',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADiaS0ypheplgzp49svlkr1Quo38xRmNg',
    appId: '1:885465995791:android:85df5d97c4e6d01cb4217a',
    messagingSenderId: '885465995791',
    projectId: 'authenticated-user-dashb-b0b3f',
    storageBucket: 'authenticated-user-dashb-b0b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_u2IxxjiNMT2tbeYIu1mHSTT0TB62CrI',
    appId: '1:885465995791:ios:33489848e3ee5f73b4217a',
    messagingSenderId: '885465995791',
    projectId: 'authenticated-user-dashb-b0b3f',
    storageBucket: 'authenticated-user-dashb-b0b3f.firebasestorage.app',
    iosBundleId: 'com.example.authenticatedUserDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_u2IxxjiNMT2tbeYIu1mHSTT0TB62CrI',
    appId: '1:885465995791:ios:33489848e3ee5f73b4217a',
    messagingSenderId: '885465995791',
    projectId: 'authenticated-user-dashb-b0b3f',
    storageBucket: 'authenticated-user-dashb-b0b3f.firebasestorage.app',
    iosBundleId: 'com.example.authenticatedUserDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_nI4LsQkKBwvYtA0zYZ7gdQBYR1u_OGg',
    appId: '1:885465995791:web:1ffb8fe173df0ef7b4217a',
    messagingSenderId: '885465995791',
    projectId: 'authenticated-user-dashb-b0b3f',
    authDomain: 'authenticated-user-dashb-b0b3f.firebaseapp.com',
    storageBucket: 'authenticated-user-dashb-b0b3f.firebasestorage.app',
    measurementId: 'G-N0VNHZ3756',
  );
}
